spring.application.name=sistema-turismo-cliente-web

# Porta diferente do projeto sistema-turismo (T7), que roda na porta 8080 (padrão)
server.port=8081

# Endereço da API REST do projeto sistema-turismo (T7)
api.sistema-turismo.base-url=http://localhost:8080

spring.thymeleaf.cache=false
